### ISSUE TITLE
FRONTEND - Исправить опечатки в названии модулей или в названии файлов

### ISSUE THREAD

**Issue by 4uku** [Prostoe-menu/prostoemenu_dev#121]
Во время сборки с помощью команды npm run build вылезли ошибки:

[front/src/components/Toast/Toast.jsx #](https://github.com/Prostoe-menu/prostoemenu_dev/blob/172bef8432c0cc4a8c4ce295f618cebb3287d1d7/front/src/components/Toast/Toast.jsx#L5)

[front/src/components/Toast/ToastNotifications.jsx #](https://github.com/Prostoe-menu/prostoemenu_dev/blob/172bef8432c0cc4a8c4ce295f618cebb3287d1d7/front/src/components/Toast/ToastNotifications.jsx#L5)

[front/src/components/PageTitle/PageTitle.jsx #](https://github.com/Prostoe-menu/prostoemenu_dev/blob/172bef8432c0cc4a8c4ce295f618cebb3287d1d7/front/src/components/PageTitle/PageTitle.jsx#L2)

в этих файлах импортируются данные из файла, начинающегося с заглавной буквы, в то время как название самого файла в проекте начинается со строчной буквы. 

обязательно проверить работоспособность создания сборки после исправления!

**Comment by MZ-87** [comment]
Баг исправлен в ПР #120
