### ISSUE TITLE
FRONTEND - Карточка рецепта на главной -  Звезды

### ISSUE THREAD

**Issue by MZ-87** [Prostoe-menu/prostoemenu_dev#125]
Разработать скрипт, который будет отрисовывать на карточке рецепта определённое количество звезд с заливкой (star-filled.svg) и без нее (star.svg) в зависимости от сложности рецепта
![image](https://github.com/Prostoe-menu/prostoemenu_dev/assets/104425091/db7b78ee-57ab-42ae-ad41-2c1ddbec34bb)

**Comment by Grimlerih** [comment]
возьму в работу
