### ISSUE TITLE
FRONTEND - Главная- Адаптив формы поиска

### ISSUE THREAD

**Issue by makholodova** [Prostoe-menu/prostoemenu_dev#212]
Надо сделать адаптив формы поиска на главной

![image](https://github.com/user-attachments/assets/271a3618-ac04-4deb-9495-0cef2474c827)

[Ссылка на дизайн](https://www.figma.com/design/hJUN2hrhTRCc5OxAe5NjE1/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%9C%D0%B5%D0%BD%D1%8E-v1.1-MVP?node-id=4061-13497&t=g9oGtTqu2dMc1xPi-4)

Актуальные макеты подписаны Каталог/MVP/Адаптив

![Каталог/MVP/Адаптив](https://github.com/user-attachments/assets/f0e1d4e7-518a-4066-a961-1d00928a876b)

**Comment by makholodova** [comment]
Сделать адаптив

https://www.figma.com/design/hJUN2hrhTRCc5OxAe5NjE1/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%9C%D0%B5%D0%BD%D1%8E-v1.1-MVP?node-id=891-3187&t=0NaAGdd2PFMFcWxP-0

**Comment by helgy55** [comment]
https://www.figma.com/design/hJUN2hrhTRCc5OxAe5NjE1/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%9C%D0%B5%D0%BD%D1%8E-v1.1-MVP?node-id=4024-27210&node-type=frame&t=u3cW6kRvPZrEgdzT-0
![2024-09-27 at 02-22-02](https://github.com/user-attachments/assets/e524472b-221c-4a21-8bd4-2ae6642266e7)
имеем: **_ведите название продукта_**
там же, правее : **_начните вводить название продукта_**.
![image](https://github.com/user-attachments/assets/fe990950-1eb3-4575-87bf-0b6f5cfb7f07)
Противоречие. **_Причина:_** эти поля - фрейм компоненты (это имплементации, реализации "главного компонента"), помечены крупным ромбом, обозначение слабо-голубым цветом. 
А их прототип "main component" имеет оригинал "найти компонент." (4 ромбика, образуют крупный ромб)
Это удобнее отвязать от правок в "implement", и исправить "main component" на требуемый текст "начните вводить название продукта".
**_В вёрстке этой проблемы нет_**. Если не к месту сказал, прошу ногами не пинать. При уменьшении ширины экрана как должна выглядеть главная страница (адаптивы?)?
1440 (есть), а для планшета, а для смартфонов (есть и 1080px, и 360px шириной). На каких значениях в пикселях адаптируется вёрстка?
дизайнер-верстальщик-фронтендер "из одной бочки налиты".
